# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6717cb8a51440e53900640a0f56d8d5a939cfc9f691f7788d50f3d6216483fde32bc62ebf4630cc6403d0af40d4faaae3a08d2489f1dc9171a755cc0461b394

test:
  secret_key_base: 6e0db8a471606cff5e642fd6736dd61c5e52f8bc7659766a224f718ea4c0f96df27d74bcb189c998ca39b0982ce794f1ca4a9d43be59cee967ea72adf314ce4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
